version: "3"
services:
  synctest:
    build: .

    image: konogan/synctest

    environment:
      - PORT=3004

    ports:
      - "3004:3004"

    expose: 
      - "3004"
   
    command: node app/app.js
