# Use this file in PORTAINER  Stack editor

version: "3"
services:
  simple:
    image: registry-recette.aws.lagardere-active.com/konogan/synctest:latest
    command: "node app.js"
    deploy:
      labels:
        traefik.backend: "synctest"
        traefik.frontend.rule: "Host:dev-kcossec.lagardere-active.com"
        traefik.port: "3004"
        traefik.docker.network: "webgateway"
        traefik.enable: "true"   
    
    networks:
     - webgateway

networks:
  webgateway:
    external:
      name: webgateway
